return {}

-- return {
--   "itchyny/lightline.vim",
--   event = "VeryLazy",
--   lazy = true,
--   config = function()
--
--     vim.g.lightline = {
--       colorscheme = "powerline",
--       active = {
--         left = {
--           { "mode", "paste" },
--           { "filename", "modified" },
--         },
--         right = {
--           { "lineinfo" },
--           { "percent" },
--           { "absolutepath", "fileformat", "fileencoding", "filetype" },
--         },
--       },
--       -- component_function = {
--       --   lsp_name = "GetLsp",
--       -- },
--       enable = {
--         tabline = 0,
--       },
--     }
--   end,
-- }
